spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    driver-class-name: org.postgresql.Driver
    username: quan
    password: Quan65122003
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    payment-url: http://localhost:8222/api/v1/payments
    product-url: http://localhost:8222/api/v1/products